'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateRec

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''txtJobno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobno As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlJobsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJobsite As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkNextmonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNextmonth As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''DropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlLotof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLotof As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtsalemandis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsalemandis As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtConsigneecode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsigneecode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNameEngConsign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameEngConsign As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress5 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlCommodity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCommodity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQuantityBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityBox As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlquanbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlquanbox As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVolume As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlvolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlvolume As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlvolume2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlvolume2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtVolume2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVolume2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtShipto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipto As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtActual1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActual1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtORGN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtORGN1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDSTN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDSTN1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtActual2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActual2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtORGN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtORGN2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDSTN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDSTN2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtActual3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActual3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtORGN3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtORGN3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDSTN3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDSTN3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtActual4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActual4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtORGN4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtORGN4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDSTN4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDSTN4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlShippercode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlShippercode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNameEngShipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameEngShipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1Shipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1Shipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2Shipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2Shipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3Shipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3Shipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4Shipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4Shipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress5Shipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress5Shipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEmailShipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailShipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtQuantityOfPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityOfPart As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQuantityOfParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuantityOfParty As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWeight As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtMAWB_BL_TWB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMAWB_BL_TWB As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFLT_Voy_TruckDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFLT_Voy_TruckDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlFreight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFreight As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBilling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBilling As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPacket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPacket As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWeightActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeightActual As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPacket2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPacket2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWeightActual2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeightActual2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPacket3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPacket3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWeightActual3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeightActual3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPacket4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPacket4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWeightActual4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeightActual4 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpProductCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboImpTariffCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboImpTariffCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtImpDesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpDesc1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chkImpEnable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImpEnable1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtImpDesc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpDesc2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chkImpEnable2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImpEnable2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtImpDesc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpDesc3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chkImpEnable3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImpEnable3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtImpProductAttribute1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpProductAttribute1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpProductAttribute2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpProductAttribute2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboImpTariffSequence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboImpTariffSequence As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtImpCustomsProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpCustomsProductCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpDutyType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpDutyType As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpValueRateP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpValueRateP As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpSpecificRateP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpSpecificRateP As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExemptDuty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExemptDuty As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpSurchargeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpSurchargeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExciseRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExciseRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExciseSpcRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExciseSpcRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExemptExcise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExemptExcise As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpValueRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpValueRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpValueRateAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpValueRateAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpFactoryNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpFactoryNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboImpStatisticalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboImpStatisticalCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtImpProductYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpProductYear As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpSpeciticRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpSpeciticRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpSpecificCal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpSpecificCal As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExemptVat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExemptVat As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExciseNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExciseNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExciseRatePay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExciseRatePay As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExciseSpcRatePay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExciseSpcRatePay As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpPriviege control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpPriviege As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboImpBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboImpBrand As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboImpCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboImpCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtImpExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpEstablishNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpEstablishNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpProductCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpDesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpDesc1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chkExpEnable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExpEnable1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtExpDesc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpDesc2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chkExpEnable2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExpEnable2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtExpDesc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpDesc3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chkExpEnable3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExpEnable3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtExpProductAttribute1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpProductAttribute1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpProductAttribute2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpProductAttribute2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboExpTariffSequence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboExpTariffSequence As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExpCustomsProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpCustomsProductCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpFomulaNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpFomulaNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpBOINo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpBOINo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpDutyType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpDutyType As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpQtyCarton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpQtyCarton As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpWeightCarton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpWeightCarton As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpValueRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpValueRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpValueRateAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpValueRateAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpFactoryNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpFactoryNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboExpTariffCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboExpTariffCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dcboExpStatisticalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboExpStatisticalCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Text20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text20 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpProductYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpProductYear As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExp19BisTranNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExp19BisTranNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpBondFormulaNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpBondFormulaNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpPriceForeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpPriceForeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpQtyPallet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpQtyPallet As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Text26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text26 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboExpCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboExpCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExpExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpEstablishNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpEstablishNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboProductUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProductUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtProductWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductWidth As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductHeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductLeng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductLeng As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductVolume As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboUnitofVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboUnitofVolume As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboPackageUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPackageUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPackageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageWidth As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageHeigh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageHeigh As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageLenght control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageLenght As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageCarton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageCarton As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageVolume As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboPackageofUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPackageofUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarks As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtEAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEAS As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomer As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOwner As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQty As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btAdd As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btModify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btModify As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btDel As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtGenCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGenCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cdbGroupGoods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cdbGroupGoods As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCodeGoods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodeGoods As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''rbtEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtEnable As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtDisable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtDisable As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtCodeCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodeCustomers As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtNoCodeGoods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoCodeGoods As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCodeSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodeSize As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cdbGroupColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cdbGroupColor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCodeColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodeColor As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
