'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomsInvoice

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''btnAddNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNew As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEdit As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSaveNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNew As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSaveEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveEdit As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtReferenceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReferenceNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CustomsConfirmDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomsConfirmDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender2 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtInvoiceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInvoice As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtPurechaseOrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPurechaseOrderNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dtpInvoiceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpInvoiceDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender3 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''dtpDeliveryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpDeliveryDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''dtpReferenceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpReferenceDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender4 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''header_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents header_ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtExporterCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExporterCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnShipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShipper As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtExportEng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExportEng As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtStreet_Number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStreet_Number As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistrict As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtSubProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubProvince As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProvince As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPostCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCompensateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompensateCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountry As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboPurchaseCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboPurchaseCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPurchaseCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPurchaseCountry As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cboDestinationCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDestinationCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDestinationCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinationCountry As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboTermofPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboTermofPayment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dcboTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboTerm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTotalNetWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalNetWeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtSumItemWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSumItemWeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalGrossWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalGrossWeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtVolumAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVolumAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalQuantity As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalQuantityINV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalQuantityINV As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtConsigneeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsigneeCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnSCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSCon As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtConsignneeEng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsignneeEng As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtConsignneeStreet_Number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsignneeStreet_Number As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtConsignneeDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsignneeDistrict As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtConsignneeSubProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsignneeSubProvince As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtConsignneeProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsignneeProvince As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtConsignneePostCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsignneePostCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtConsignneeEMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsignneeEMail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboCarLicense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboCarLicense As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dcboDriverName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboDriverName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dcboTotalInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboTotalInvoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTotalInvoiceAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalInvoiceAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalInvoiceAmount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalInvoiceAmount1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboForwarding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboForwarding As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtForwardingAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForwardingAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtForwardingAmount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForwardingAmount1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboFreight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboFreight As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFreightAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreightAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFreightAmount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreightAmount1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboInsurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboInsurance As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtInsuranceAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsuranceAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtInsuranceAmount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsuranceAmount1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboPackingCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboPackingCharge As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPackingChargeAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackingChargeAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackingChargeAmount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackingChargeAmount1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboForeignInland control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboForeignInland As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtForeignInlandAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForeignInlandAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtForeignInlandAmount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForeignInlandAmount1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboLandingCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboLandingCharge As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtLandingChargeAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLandingChargeAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLandingChargeAmount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLandingChargeAmount1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboOtherCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboOtherCharge As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTotalInvoiceTHBAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalInvoiceTHBAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalInvoiceTHBAmount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalInvoiceTHBAmount1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''rdbDiffAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbDiffAmount As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtdatepickerTransmitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerTransmitDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderTransmitDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderTransmitDate As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''rdbDiffWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbDiffWeight As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbNotifyParty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbNotifyParty As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbOnBehalfOf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbOnBehalfOf As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''chkEnablebehalf_EASJOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnablebehalf_EASJOB As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''job_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtEASExporterCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASExporterCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOwner As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtEASNameEng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASNameEng As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASStreet_Number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASStreet_Number As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASDistrict As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASSubProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASSubProvince As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASProvince As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASPostCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASPostCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASCompensateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASCompensateCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomerCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShip As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtCustomerEng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerEng As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtCustomerEMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerEMail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomerTelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerTelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomerFaxNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerFaxNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomerContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerContactPerson As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CoutItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoutItem As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''Use control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Use As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtEASInvREFNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASInvREFNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASLOTNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASLOTNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomerRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerRefNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtSpecialInstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecialInstruction As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboShipMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboShipMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dcboDeliveryTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboDeliveryTerm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dcboShippingMark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboShippingMark As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtShippingCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShippingCompany As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtShippingAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShippingAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtEASRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASRemark As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtTotalCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalCurrency As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASCustomerCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASCustomerCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnBill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBill As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtEASCustomerEng1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASCustomerEng1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASCustomerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASCustomerAddress As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtEASEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASTelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASTelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASFaxNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASFaxNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASContactPerson As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''deetail_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deetail_ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dcboBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboBrand As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtProductYea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductYea As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboNatureOfTrn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboNatureOfTrn As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dcboPurchaseCtry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboPurchaseCtry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dcboOriginCtry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboOriginCtry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtItemNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItemNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtProductDesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductDesc1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductDesc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductDesc2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductDesc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductDesc3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtInvQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvQty As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboInvQtyUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboInvQtyUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtInvQtyUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvQtyUnit As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboWeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboWeightUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtWeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeightUnit As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboQuantityUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboQuantityUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQuantityUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityUnit As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPriceForeigh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceForeigh As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPriceForeighAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceForeighAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPriceBath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceBath As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPriceBathAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceBathAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTariffCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTariffCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtStatisticalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStatisticalCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTariffSequence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTariffSequence As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductAttribute1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductAttribute1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductAttribute2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductAttribute2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPriceIncreaseForeign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceIncreaseForeign As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPriceIncreseBath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceIncreseBath As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDeclarationLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeclarationLine As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFormulaNo_ItemDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFormulaNo_ItemDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtBOILicenseNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBOILicenseNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txt19BisTransferNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt19BisTransferNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtBondFurmulaNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBondFurmulaNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtItemRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItemRemark As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''dcboForwardingCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboForwardingCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtForwardingForiegnAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForwardingForiegnAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtForwardingExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForwardingExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtForwardingBathAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForwardingBathAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboFreightCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboFreightCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFreightForiegnAmo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreightForiegnAmo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFreightExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreightExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFreightBathAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreightBathAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboInsuranceCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboInsuranceCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtInsuranceForiegnAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsuranceForiegnAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtInsuranceExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsuranceExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtInsuranceBathAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsuranceBathAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboPackageChargeCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboPackageChargeCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPackageChargeFoiegnAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageChargeFoiegnAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageChargeExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageChargeExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageChargeBathAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageChargeBathAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboForeighnCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboForeighnCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtForeighnForiegnAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForeighnForiegnAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtForeighnExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForeighnExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtForeighnBathAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForeighnBathAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboLandingChargeCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboLandingChargeCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtLandingChargeForiegnAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLandingChargeForiegnAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLandingChargeExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLandingChargeExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLandingChargeBathAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLandingChargeBathAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboOtherChargeCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboOtherChargeCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtOtherChargeForiegnAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherChargeForiegnAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOtherChargeExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherChargeExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOtherChargeBathAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherChargeBathAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnAddNewItem_ItemDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewItem_ItemDetail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSaveModify_ItemDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveModify_ItemDetail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDelete_ItemDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_ItemDetail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnCreatePacking_ItemDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreatePacking_ItemDetail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''dgvLotNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvLotNo As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''list_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents list_ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtPackProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackProductCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''NetWeight_PACKINGLIST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NetWeight_PACKINGLIST As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtPackProductDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackProductDesc As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtCustomerPN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerPN As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboPackCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboPackCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPackCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackCountry As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPLTAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPLTAmount As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPLTQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPLTQuantity As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackWeight As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPackVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackVolume As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''rdbCM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbCM As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbInch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbInch As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtOwnerPN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOwnerPN As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboPackUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboPackUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPackUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackUnit As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCTNAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCTNAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackQuantity As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackGross control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackGross As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPONo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWidth As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLeng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLeng As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPLTNetAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPLTNetAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboUnitPLT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboUnitPLT As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPLTUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPLTUnit As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCTNNetAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCTNNetAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dcboCTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dcboCTN As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCTNUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCTNUnit As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalText As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''chkCopyToDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCopyToDetail As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''btnAddNewItem_PACKINGLIST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewItem_PACKINGLIST As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSaveModify_PACKINGLIST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveModify_PACKINGLIST As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDelete_PACKINGLIST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_PACKINGLIST As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''TabName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Search1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Search1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upSearch1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upSearch1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgvSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvSearch As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''txtStartInvoiceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartInvoiceNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtStartExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartExporter As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtStartConsignnee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartConsignnee As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dtpStartInvoiceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpStartInvoiceDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender5 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtEndInvoiceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndInvoiceNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEndExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndExporter As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtToConsignnee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtToConsignnee As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dtpEndInvoiceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpEndInvoiceDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender6 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''plExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plExporter As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upExporter As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgvExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvExporter As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''plExporterCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plExporterCode As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upExporterCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upExporterCode As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgvExporterCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvExporterCode As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''plConsignnee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plConsignnee As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upConsignnee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upConsignnee As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgvConsignnee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvConsignnee As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''plExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plExporter1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upExporter1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgvExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvExporter1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''plShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plShipTo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upShipTo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgvShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvShipTo As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''plBillTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plBillTo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upBillTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upBillTo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgvBillTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvBillTo As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''plIEAT107 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plIEAT107 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upIEAT107 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upIEAT107 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgvIEAT107 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvIEAT107 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''txtTotalAmonut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalAmonut As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalUseAmonut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalUseAmonut As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAmonut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmonut As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtUseAmonut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUseAmonut As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dtpForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpForm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender7 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''dtpTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender9 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''Checkbox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Checkbox1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''dtpEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtpEx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender8 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''AddIEAT107_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddIEAT107_ As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
