'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InvoicePackingListRec

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ddlShipperCode_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlShipperCode_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNameShipper_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameShipper_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1Shipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1Shipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2Shipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2Shipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3Shipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3Shipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4Shipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4Shipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress5Shipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress5Shipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEmailShipper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailShipper As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtConsigneeCode_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsigneeCode_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNameConsignee_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameConsignee_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1Consignee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1Consignee As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2Consignee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2Consignee As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3Consignee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3Consignee As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4Consignee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4Consignee As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress5Consignee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress5Consignee As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEmailConsignee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailConsignee As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlOriginCountry_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOriginCountry_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtOriginCountry_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOriginCountry_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlPurchaseCountry_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPurchaseCountry_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPurchaseCountry_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPurchaseCountry_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlDestinationCountry_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDestinationCountry_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDestinationCountry_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestinationCountry_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlTermOfPayment_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTermOfPayment_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTerm_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTerm_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTotalNewWeight_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalNewWeight_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtSumItemWeight_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSumItemWeight_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalGrossWeight_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalGrossWeight_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalVolume_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalVolume_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalQuantityPack_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalQuantityPack_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalQuantityINV_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalQuantityINV_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlTotalInvoice_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTotalInvoice_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTotalInvoice1_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalInvoice1_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTotalInvoice2_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalInvoice2_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlForwarding_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlForwarding_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtForwarding1_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForwarding1_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtForwarding2_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForwarding2_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlFreight_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFreight_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFreight1_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreight1_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFreight2_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFreight2_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlInsurance_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInsurance_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtInsurance1_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsurance1_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtInsurance2_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsurance2_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlPackingCharge_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPackingCharge_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPackingCharge1_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackingCharge1_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackingCharge2_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackingCharge2_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlHandingCharge_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHandingCharge_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtHandingCharge1_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHandingCharge1_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtHandingCharge2_invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHandingCharge2_invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlLandingCharge_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLandingCharge_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtLandingCharge1_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLandingCharge1_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLandingCharge2_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLandingCharge2_Invoice As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlTotalInvoiceTHB_Invoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTotalInvoiceTHB_Invoice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Text1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Text2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtInvoiceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtLOTNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLOTNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPartDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartDesc As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtMeasurement_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMeasurement_Detail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOwnP_N control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOwnP_N As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomerP_N control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerP_N As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtQuantity_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity_Detail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlUnitQuantity_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUnitQuantity_Detail As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtGrossWeight_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGrossWeight_Detail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlUnit_GrossWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUnit_GrossWeight As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCountryOfOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCountryOfOrigin As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSaveNew_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNew_Detail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSaveModify_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveModify_Detail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDelete_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_Detail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnCencel_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCencel_Detail As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
