'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PrepareLotWH

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''btnAddHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddHead As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnEditHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditHead As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSaveAddHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAddHead As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSaveEditHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveEditHead As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''preparegoodsreceive_fieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents preparegoodsreceive_fieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtJobNo_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobNo_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnJobNoSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnJobNoSearch As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnJobNoSearch_Edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnJobNoSearch_Edit As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtdatepickerJobdate_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerJobdate_PreGoodRec As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderJobdate_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderJobdate_PreGoodRec As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtCustRefNo_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustRefNo_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOwnerCode_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOwnerCode_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnOwnerCode_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOwnerCode_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtNameOwner_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameOwner_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1Owner_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1Owner_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2Owner_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2Owner_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3Owner_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3Owner_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4Owner_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4Owner_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWHManagement_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWHManagement_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnWHManagement_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWHManagement_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtNameWHManage_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameWHManage_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1WHManage_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1WHManage_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2WHManage_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2WHManage_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3WHManage_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3WHManage_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4WHManage_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4WHManage_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomerCode0_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerCode0_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnCustomerCode_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCustomerCode_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtNameCustomer_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameCustomer_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1Customer_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1Customer_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2Customer_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2Customer_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3Customer_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3Customer_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4Customer_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4Customer_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEndUserCode_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndUserCode_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnEndUserCode_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEndUserCode_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtNameEndUser_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameEndUser_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1EndUser_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1EndUser_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2EndUser_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2EndUser_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3EndUser_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3EndUser_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4EndUser_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4EndUser_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtHandlePreson_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHandlePreson_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtdatepickerDateAssign_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerDateAssign_PreGoodRec As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderDateAssign_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderDateAssign_PreGoodRec As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''ddlCommodity_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCommodity_PreGoodRec As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQuantityPackage_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityPackage_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQuantityPackage_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuantityPackage_PreGoodRec As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQuantityPLTSkid_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityPLTSkid_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQuantityPLTSkid_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuantityPLTSkid_PreGoodRec As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtRemark_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtQuantityOfGood_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityOfGood_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQuantityOfGood_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuantityOfGood_PreGoodRec As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtWeight_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeight_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlWeight_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWeight_PreGoodRec As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtVolume_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVolume_PreGoodRec As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlVolume_PreGoodRec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVolume_PreGoodRec As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''goodreceivedetail_fieldset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents goodreceivedetail_fieldset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''JobDetailPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobDetailPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''JobDetailUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobDetailUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Repeater9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater9 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ddlWHSite_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWHSite_GoodRecDetail As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCusLOTNo_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCusLOTNo_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEASPN_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEASPN_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnEASPN_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEASPN_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtProductDesc_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductDesc_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''ddlWHLocation_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWHLocation_GoodRecDetail As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCustWHFac_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustWHFac_GoodRecDetail As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCustomerPN_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerPN_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtENDCustomer_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtENDCustomer_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnENDCustomer_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnENDCustomer_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtItemNo_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItemNo_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOwnerPN_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOwnerPN_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlMeasurement_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMeasurement_GoodRecDetail As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtWidth_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWidth_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtHight_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHight_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOrderNo_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNo_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtReceiveNo_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiveNo_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chkNotUseDate_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNotUseDate_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtdatepickerManufacturing_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerManufacturing_GoodRecDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderManufacturing_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderManufacturing_GoodRecDetail As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerReceiveDate_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerReceiveDate_GoodRecDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderReceiveDate_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderReceiveDate_GoodRecDetail As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtQuantity_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantity_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQuantity_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuantity_GoodRecDetail As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCurrency_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCurrency_GoodRecDetail As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPriceForeign_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceForeign_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPriceBath_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceBath_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''rdbShortShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbShortShip As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbOverShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbOverShip As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtLength_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLength_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductVolume_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductVolume_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPalletNo_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPalletNo_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlStatus_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatus_GoodRecDetail As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtdatepickerExpiredDate_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerExpiredDate_GoodRecDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderExpiredDate_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderExpiredDate_GoodRecDetail As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerStorageExpDate_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerStorageExpDate_GoodRecDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderStorageExpDate_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderStorageExpDate_GoodRecDetail As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtWeight_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeight_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlWeight_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWeight_GoodRecDetail As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExchangeRate_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExchangeRate_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAmount_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtBathAmount_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBathAmount_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtSupplier_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupplier_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDestination_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestination_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEntryNo_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntryNo_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtBuyer_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBuyer_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtConsignee_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsignee_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEntryItemNo_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEntryItemNo_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExporter_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExporter_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtShippingMark_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShippingMark_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtInvoice_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoice_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnAddNew_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNew_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnSaveModify_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveModify_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDelete_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnDeleteAll_GoodRecDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteAll_GoodRecDetail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtSelectFileForImport_ImportData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectFileForImport_ImportData As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''btnImport_ImportData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImport_ImportData As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''chkfollowcustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkfollowcustomer As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkOnlyWorkANS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOnlyWorkANS As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''btnCheckPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckPart As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''JobNoAddPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobNoAddPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''JobNoAddUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobNoAddUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Repeater1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''CustomerPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CustomerUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Repeater2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater2 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''OwnerPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OwnerPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''OwnerUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OwnerUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Repeater3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater3 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''WHManagePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WHManagePanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''WHManageUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WHManageUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Repeater4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater4 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''EndUserPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndUserPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EndUserUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndUserUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Repeater5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater5 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''EndCustomerPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndCustomerPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''EndCustomerUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndCustomerUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Repeater6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater6 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ProductCodePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductCodePanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ProductCodeUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductCodeUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Repeater7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater7 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''JobNoEditPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobNoEditPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''JobNoEditUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JobNoEditUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Repeater8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater8 As Global.System.Web.UI.WebControls.Repeater
End Class
