'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RptCustomsFrm

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''rdbNormalReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbNormalReport As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbCompleteReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbCompleteReport As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbNotCompleteReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbNotCompleteReport As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbIN As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdbOUT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbOUT As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''btnAddData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddData As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''rdb01_TAB01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdb01_TAB01 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdb02_TAB01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdb02_TAB01 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdb03_TAB01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdb03_TAB01 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdb04_TAB01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdb04_TAB01 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtdatepickerFromDate_TAB01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerFromDate_TAB01 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderFromDate_TAB01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderFromDate_TAB01 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerToDate_TAB01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerToDate_TAB01 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderToDate_TAB01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderToDate_TAB01 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnReport_TAB01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport_TAB01 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''rdb01_TAB02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdb01_TAB02 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdb02_TAB02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdb02_TAB02 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtdatepickerFromDate_TAB02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerFromDate_TAB02 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderFromDate_TAB02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderFromDate_TAB02 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerToDate_TAB02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerToDate_TAB02 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderToDate_TAB02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderToDate_TAB02 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnReport_TAB02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport_TAB02 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtdatepickerFromDate_TAB03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerFromDate_TAB03 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderFromDate_TAB03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderFromDate_TAB03 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerToDate_TAB03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerToDate_TAB03 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderToDate_TAB03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderToDate_TAB03 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnReport_TAB03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport_TAB03 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtdatepickerFromDate_TAB04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerFromDate_TAB04 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderFromDate_TAB04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderFromDate_TAB04 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerToDate_TAB04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerToDate_TAB04 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderToDate_TAB04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderToDate_TAB04 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnReport_TAB04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport_TAB04 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtdatepickerFromDate_TAB05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerFromDate_TAB05 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderFromDate_TAB05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderFromDate_TAB05 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerToDate_TAB05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerToDate_TAB05 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderToDate_TAB05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderToDate_TAB05 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnReport_TAB05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport_TAB05 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtdatepickerRemainProduct_TAB06 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerRemainProduct_TAB06 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderRemainProduct_TAB06 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderRemainProduct_TAB06 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnReport_TAB06 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport_TAB06 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtdatepickerFromDate_TAB07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerFromDate_TAB07 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderFromDate_TAB07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderFromDate_TAB07 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerToDate_TAB07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerToDate_TAB07 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderToDate_TAB07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderToDate_TAB07 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnReport_TAB07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport_TAB07 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtdatepickerFromDate_TAB08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerFromDate_TAB08 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderFromDate_TAB08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderFromDate_TAB08 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerToDate_TAB08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerToDate_TAB08 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderToDate_TAB08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderToDate_TAB08 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnReport_TAB08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReport_TAB08 As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
