'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SingleIssuedWH

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''txtPullSignal_BeforeTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPullSignal_BeforeTab As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtJobNo_BeforeTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJobNo_BeforeTab As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chkScrap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkScrap As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtdatepickertxtPullDateTime_beforeTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickertxtPullDateTime_beforeTab As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderPullDateTime_beforeTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderPullDateTime_beforeTab As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerDeliveryDateTime_beforeTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerDeliveryDateTime_beforeTab As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderDeliveryDateTime_beforeTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderDeliveryDateTime_beforeTab As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerComfirmDateTime_beforeTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerComfirmDateTime_beforeTab As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderComfirmDateTime_beforeTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderComfirmDateTime_beforeTab As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''ddlJobNo_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJobNo_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkMoveTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMoveTo As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtCustRefNo_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustRefNo_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnRejectMoveTo_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRejectMoveTo_IssueCon As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''ddlWHSite_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWHSite_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlExporterCode_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExporterCode_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNameExporter_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameExporter_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1Exporter_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1Exporter_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2Exporter_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2Exporter_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3Exporter_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3Exporter_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4Exporter_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4Exporter_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlOwnerCode_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOwnerCode_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNameOwner_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameOwner_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1Owner_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1Owner_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2Owner_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2Owner_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3Owner_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3Owner_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4Owner_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4Owner_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlCommodity_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCommodity_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQuantityPackage_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityPackage_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQuantityPackage_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuantityPackage_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQuantityPLTSkid_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityPLTSkid_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQuantityPLTSkid_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuantityPLTSkid_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txttxtQuantityPicked_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttxtQuantityPicked_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQuantityPicked_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuantityPicked_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSumQTY_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSumQTY_IssueCon As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtConsigneeCode_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsigneeCode_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNameConsignee_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameConsignee_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1Consignee_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1Consignee_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2Consignee_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2Consignee_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3Consignee_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3Consignee_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4Consignee_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4Consignee_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlShipToCode_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlShipToCode_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNameShipTo_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameShipTo_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress1ShipTo_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1ShipTo_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress2ShipTo_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2ShipTo_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress3ShipTo_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3ShipTo_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAddress4ShipTo_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress4ShipTo_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtQuantityOfGood_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuantityOfGood_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQuantityOfGood_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuantityOfGood_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtWeight_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeight_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlWeight_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWeight_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtVolume_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVolume_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''DropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQTYDiscrepancy_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQTYDiscrepancy_IssueCon As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlQTYDiscrepancy_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQTYDiscrepancy_IssueCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnConfirmIssued_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmIssued_IssueCon As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnRejectConfirm_IssueCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRejectConfirm_IssueCon As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''ddlWHSite_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWHSite_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCusLOTNo_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCusLOTNo_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlEASPN_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEASPN_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlWHLocation_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWHLocation_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCustWHFac_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustWHFac_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCustomerPN_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerPN_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlENDCustomer_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlENDCustomer_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtItemNo_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtItemNo_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOwnerPN_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOwnerPN_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlMeasurement_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMeasurement_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtWeidth_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeidth_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtHight_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHight_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOrderNo_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNo_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtReceiveNo_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceiveNo_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chkNotUseDate_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNotUseDate_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtdatepickerManufacturing_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerManufacturing_ConfirmIssue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderManufacturing_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderManufacturing_ConfirmIssue As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtdatepickerReceiveDate_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerReceiveDate_ConfirmIssue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderReceiveDate_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderReceiveDate_ConfirmIssue As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtPickQTY_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPickQTY_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlPickQTY_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPickQTY_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCurrency_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCurrency_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPriceForeign_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceForeign_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPriceBath_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceBath_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtLength_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLength_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductVolume_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductVolume_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPalletNo_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPalletNo_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlStatus_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatus_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlType_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlType_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtdatepickerExpiredDate_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerExpiredDate_ConfirmIssue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderExpiredDate_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderExpiredDate_ConfirmIssue As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtIssueQTY_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIssueQTY_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWeight_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeight_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ddlWeight_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWeight_ConfirmIssue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtExchangeRate_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExchangeRate_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAmount_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtBathAmount_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBathAmount_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtdatepickerReceiveDate_Button_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdatepickerReceiveDate_Button_ConfirmIssue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtenderReceiveDate_Button_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtenderReceiveDate_Button_ConfirmIssue As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtWHLocation_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWHLocation_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnIssue_ConfirmIssue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIssue_ConfirmIssue As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
