'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewGoods

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''txtProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomerPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerPart As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCreateBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreateBy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCreateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreateDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductPO As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEndUserPart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndUserPart As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtUpdateBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUpdateBy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtUpdateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUpdateDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtMinimunStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMinimunStock As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAdjustment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdjustment As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtDamageQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDamageQty As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAvailableQTY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAvailableQTY As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpProductCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpTariffCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpTariffCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpDesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpDesc1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpDesc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpDesc2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpDesc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpDesc3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpProductAttribute1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpProductAttribute1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpProductAttribute2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpProductAttribute2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpTariffSequence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpTariffSequence As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpCustomsProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpCustomsProductCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpDutyType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpDutyType As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpValueRateP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpValueRateP As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpSpecificRateP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpSpecificRateP As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExemptDuty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExemptDuty As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpSurchargeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpSurchargeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExciseRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExciseRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExciseSpcRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExciseSpcRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExemptExcise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExemptExcise As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpValueRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpValueRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpValueRateAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpValueRateAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpFactoryNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpFactoryNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpStatisticalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpStatisticalCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpProductYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpProductYear As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpSpeciticRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpSpeciticRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpSpecificCal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpSpecificCal As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExemptVat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExemptVat As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExciseNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExciseNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExciseRatePay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExciseRatePay As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExciseSpcRatePay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExciseSpcRatePay As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpPriviege control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpPriviege As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpBrand As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpCurrency As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtImpEstablishNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImpEstablishNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpProductCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpDesc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpDesc1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpDesc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpDesc2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpDesc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpDesc3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpProductAttribute1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpProductAttribute1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpProductAttribute2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpProductAttribute2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpTariffSequence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpTariffSequence As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpCustomsProductCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpCustomsProductCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpFomulaNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpFomulaNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpBOINo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpBOINo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpDutyType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpDutyType As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpQtyCarton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpQtyCarton As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpWeightCarton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpWeightCarton As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpValueRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpValueRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpValueRateAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpValueRateAmount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpFactoryNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpFactoryNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpTariffCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpTariffCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpStatisticalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpStatisticalCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Text20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text20 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpProductYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpProductYear As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExp19BisTranNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExp19BisTranNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpBondFormulaNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpBondFormulaNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpPriceForeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpPriceForeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpQtyPallet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpQtyPallet As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPriviege control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriviege As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpCurrency As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpExchangeRate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtExpEstablishNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpEstablishNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductUnit As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductWidth As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductHeight As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductLeng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductLeng As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtProductVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductVolume As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtUnitofVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitofVolume As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageUnit As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageWidth As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageHeigh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageHeigh As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageLenght control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageLenght As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageCarton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageCarton As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageVolume As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPackageofUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackageofUnit As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarks As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtEAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEAS As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomer As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOwner As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQty As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
