'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class LKBwarehouseEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=LKBwarehouseEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AccessSystem() As DbSet(Of AccessSystem)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property tblBranch() As DbSet(Of tblBranch)
    Public Overridable Property tblCodeMaster() As DbSet(Of tblCodeMaster)
    Public Overridable Property tblDepartment() As DbSet(Of tblDepartment)
    Public Overridable Property tblLogUser() As DbSet(Of tblLogUser)
    Public Overridable Property tblParty() As DbSet(Of tblParty)
    Public Overridable Property tblProductDetail() As DbSet(Of tblProductDetail)
    Public Overridable Property tblRunningNumber() As DbSet(Of tblRunningNumber)
    Public Overridable Property tblTypeMasterCode() As DbSet(Of tblTypeMasterCode)
    Public Overridable Property tblUser() As DbSet(Of tblUser)
    Public Overridable Property tblUserGroup() As DbSet(Of tblUserGroup)

End Class
