'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCodeMaster
    Public Property MasterCodeID As Integer
    Public Property TypeID As String
    Public Property UserID As Integer
    Public Property Code As String
    Public Property Description As String
    Public Property Note As String
    Public Property FilterInd As String
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property UpdateDate As Nullable(Of Date)

    Public Overridable Property tblTypeMasterCode As tblTypeMasterCode
    Public Overridable Property tblUser As tblUser

End Class
