'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblEntryManagementWH
    Public Property LotNo As String
    Public Property EntryDate As String
    Public Property ProductOwner As String
    Public Property InvoiceNumber As String
    Public Property TransportationMode As String
    Public Property EDINo As String
    Public Property MAWB As String
    Public Property HAWB As String
    Public Property TruckWaybill As String
    Public Property BL As String
    Public Property PullSignalNo As String
    Public Property ProductDescription As String
    Public Property Package_Quantity As String
    Public Property Package_Unit As String
    Public Property Product_Quantity As String
    Public Property Product_Unit As String
    Public Property GrossWT As String
    Public Property NetWT As String
    Public Property Volume As String
    Public Property UnitPrice_THB As String
    Public Property UnitPrice_USD As String
    Public Property InvoiceValue_USD As String
    Public Property InvoiceValue_ExchangeRate As String
    Public Property InvoiceValue_THB As String
    Public Property InvoiceBalance As String
    Public Property CustomsValue_Total_THB As String
    Public Property CustomsValue_Balance_THB As String
    Public Property CustomerName As String
    Public Property ActiveDate_Receiving As String
    Public Property ActiveDate_Issuign As String
    Public Property Remarks As String
    Public Property StockBalance As String
    Public Property Editby As String
    Public Property rowguid As System.Guid

End Class
