'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblImpLogFlight
    Public Property LotNo As String
    Public Property Number As Decimal
    Public Property FlightNo As String
    Public Property DateFlight As Nullable(Of Date)
    Public Property House As String
    Public Property HouseNo As String
    Public Property Quantity As Nullable(Of Double)
    Public Property UnitQuantity As String
    Public Property Userby As String
    Public Property Updateby As Nullable(Of Date)
    Public Property rowguid As System.Guid

End Class
