'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPartyAddress
    Public Property PartyAddressCode As Decimal
    Public Property PartyCode As String
    Public Property AddressType As String
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property Address3 As String
    Public Property Address4 As String
    Public Property ZipCode As String
    Public Property AreaCode As String
    Public Property Attn As String
    Public Property Tel As String
    Public Property Fax As String
    Public Property Web As String
    Public Property email As String
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property UpdateDate As Nullable(Of Date)

End Class
