'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblStatusBalance
    Public Property PartyCode As String
    Public Property JobNo As String
    Public Property InvoiceNo As String
    Public Property Status As Nullable(Of Integer)
    Public Property InvoiceDate As Nullable(Of Date)
    Public Property JobDate As Nullable(Of Date)
    Public Property UseAmount As Nullable(Of Decimal)
    Public Property DeliveryDate As Nullable(Of Date)
    Public Property ReturnDate As Nullable(Of Date)
    Public Property RenewDate As Nullable(Of Date)
    Public Property Qty As Nullable(Of Decimal)
    Public Property QtyUnit As String
    Public Property ReturnInvNo As String
    Public Property ActualReturnDate As Nullable(Of Date)
    Public Property CreateBy As String
    Public Property CreateDate As Nullable(Of Date)
    Public Property UpdateBy As String
    Public Property UpdateDate As Nullable(Of Date)
    Public Property StatusRenew As Nullable(Of Integer)

End Class
