'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblWHReceiveScantoTemp
    Public Property JobNo As String
    Public Property ProductCode As String
    Public Property CustomerPN As String
    Public Property OwnerPN As String
    Public Property ProductDesc As String
    Public Property CustomerLOTNo As String
    Public Property ReceiveDate As Nullable(Of Date)
    Public Property Quantity As Nullable(Of Double)
    Public Property QuantityUnit As String
    Public Property BoxNo As String
    Public Property PalletNo As String
    Public Property TransectionDate As Nullable(Of Date)
    Public Property UserBy As String

End Class
