'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblWHPickPackChecking
    Public Property NewProductCode As String
    Public Property Row As Decimal
    Public Property LOTNo As String
    Public Property WHSite As String
    Public Property WHLocation As String
    Public Property WHSource As String
    Public Property EndCustomer As String
    Public Property EASPN As String
    Public Property CustomerLOTNo As String
    Public Property ItemNo As Nullable(Of Double)
    Public Property ProductDese As String
    Public Property CustomerPN As String
    Public Property OwnerPN As String
    Public Property InvOty As Nullable(Of Double)
    Public Property CurrentQuantity As Nullable(Of Double)
    Public Property UnitCurrentQuantity As String
    Public Property QuantityPrequire As Nullable(Of Double)
    Public Property UnitQuantityPrequire As String
    Public Property Userby As String
    Public Property LastUpdate As Nullable(Of Date)
    Public Property rowguid As System.Guid

End Class
