'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VtestLotImp
    Public Property LOTDate As Nullable(Of Date)
    Public Property EASLOTNo As String
    Public Property InvoiceNo As String
    Public Property MAWB As String
    Public Property Quantity As Nullable(Of Double)
    Public Property Pallet As Nullable(Of Double)
    Public Property Weight As Nullable(Of Double)
    Public Property IEATNo As String
    Public Property IEATPermit As String
    Public Property EntryNo As String
    Public Property ProductName As String
    Public Property DOCode As String
    Public Property DeliveryDate As Nullable(Of Date)
    Public Property Useby As String

End Class
